openapi: 3.0.2 
info:
  title: Course Class Service API Specification
  description: OpenAPI for Course Class API
  version: 1
servers:
  - url: http://localhost:8000
    description: Course Class Service API Server
externalDocs:
  - url: https://github.com/catherinevania/microservice-obe
    description: Github Repository
paths:
  /course-classes:
    get:

    post:

  /course-classes/{id}:
    get:
      summary: Get a class by ID
      description: View a class with certain ID
      parameters:
        - name: id
          in: path
          description: ID of the class to retrieve
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Succesfully get class by ID
          content: 
            application/json:
              schema: 
                type: object
                properties:
                    name:
                      type: string
                    course_id:
                      type: integer
                    syllabus_id:
                      type: integer
                    thumbnail_img:
                      type: string
                      contentMediaType: image/png
                      contentEncoding: base64     
        '404':
          description: Course not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string 

    patch:
      summary: Update existing course classes
      description: Update certain attributes of an existing course classes in database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                course:
                  type: integer
                  description: The course classes's ID
                  enum:
                  - 1
                  - 2
                  - 3
                  - 4
                  - 5
                  required: true
                class-name:
                  type: string
                  description: The name of course classes
                  required: true
                thumbnail_img:
                  type: string
                  format: binary
                  description: The binary data of the thumbnail image file
                  required: true
      responses:
        '200':
          description: Succesfully update course classes
          content: 
            application/json:
              schema: 
                schema:
              type: object
              properties:
                course:
                  type: integer
                  description: The course classes's ID
                  enum:
                  - 1
                  - 2
                  - 3
                  - 4
                  - 5
                  required: true
                class-name:
                  type: string
                  description: The name of course classes
                  required: true
                thumbnail_img:
                  type: string
                  format: binary
                  description: The binary data of the thumbnail image file
                  required: true
        '404':
          description: Course classes not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

    delete:
      summary: Delete existing class
      description: Delete existing class from database
      parameters:
        - name: id
          in: path
          description: ID of the class to delete
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Succesfully delete the class
          content: 
            application/json:
              schema: 
                type: object
                properties:
                  success: 
                    type: boolean
        '404':
          description: Class not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string