openapi: 3.0.2 
info:
  title: Course Class Service API Specification
  description: OpenAPI for Course Class API
  version: 1
servers:
  - url: http://localhost:8000
    description: Course Class Service API Server
externalDocs:
  - url: https://github.com/catherinevania/microservice-obe
    description: Github Repository
paths:
  /course-classes:
    get:
      summary: Get all classes
      description: View all classes from database
      responses:
        '200':
          description: Succesfully get all classes
          content: 
            application/json: 
              schema: 
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    course_id:
                      type: integer
                    syllabus_id:
                      type: integer
                    thumbnail_img:
                      type: string
                      contentMediaType: image/png
                      contentEncoding: base64 
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    post:
      summary: Create new class
      description: Create new class to database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                course_id: 
                  type: integer
                  description: The course's id
                  example: 1
                  minLength: 1
                  maxLength: 255
                  required: true
                syllabus_id: 
                  type: integer
                  description: The syllabus's id
                  example: 2
                  minLength: 1
                  maxLength: 255
                  required: true
                name:
                  type: string
                  description: The class's name
                  example: Class A
                  minLength: 1
                  maxLength: 255
                  required: true
                thumbnail_img:
                  type: string
                  description: The thumbnail image for the class
                  example: A class's thumbnail image
                  contentMediaType: image/png, image/jpg, image/jpeg, image/svg
                  contentEncoding: base64
                  required: false
      responses:
        '200':
          description: Succesfully create class
          content: 
            application/json:
              schema: 
                type: object
                properties:
                    course_id:
                      type: integer
                    syllabus_id:
                      type: integer
                    name: 
                      type: string
                    thumbnail_img:
                      type: string
        '401':
          description: User Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '409':
          description: Conflict - invalid duplicates
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /course-classes/{id}:
    get:
      summary: Get a class by ID
      description: View a class with certain ID
      parameters:
        - name: id
          in: path
          description: ID of the class to retrieve
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Succesfully get class by ID
          content: 
            application/json:
              schema: 
                type: object
                properties:
                    name:
                      type: string
                    course_id:
                      type: integer
                    syllabus_id:
                      type: integer
                    thumbnail_img:
                      type: string
                      contentMediaType: image/png
                      contentEncoding: base64     
        '404':
          description: Course not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string 

    patch:
      summary: Update existing course classes
      description: Update certain attributes of an existing course classes in database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                course:
                  type: integer
                  description: The course classes's ID
                  enum:
                  - 1
                  - 2
                  - 3
                  - 4
                  - 5
                  required: true
                class-name:
                  type: string
                  description: The name of course classes
                  required: true
                thumbnail_img:
                  type: string
                  format: binary
                  description: The binary data of the thumbnail image file
                  required: true
      responses:
        '200':
          description: Succesfully update course classes
          content: 
            application/json:
              schema: 
                schema:
              type: object
              properties:
                course:
                  type: integer
                  description: The course classes's ID
                  enum:
                  - 1
                  - 2
                  - 3
                  - 4
                  - 5
                  required: true
                class-name:
                  type: string
                  description: The name of course classes
                  required: true
                thumbnail_img:
                  type: string
                  format: binary
                  description: The binary data of the thumbnail image file
                  required: true
        '404':
          description: Course classes not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

    delete:
      summary: Delete existing class
      description: Delete existing class from database
      parameters:
        - name: id
          in: path
          description: ID of the class to delete
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Succesfully delete the class
          content: 
            application/json:
              schema: 
                type: object
                properties:
                  success: 
                    type: boolean
        '404':
          description: Class not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /course-classes/{id}/add-student:
    post:
      summary: Add new student to a course class
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                course_class_id: 
                  type: integer
                  description: The course class id
                  example: 1
                  minLength: 1
                  maxLength: 255
                  required: true
                student_user_id: 
                  type: integer
                  description: The added student id
                  example: 2
                  minLength: 1
                  maxLength: 255
                  required: true
                name:
                  type: string
                  description: The student's name
                  example: Class A
                  minLength: 1
                  maxLength: 255
                  required: true
      responses:
        '200':
          description: Succesfully added a new student
          content: 
            application/json:
              schema: 
                schema:
              type: object
              properties:
                course_class_id:
                  type: integer
                student_user_id:
                  type: integer
                name:
                  type: string       
        '404':
          description: Class not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /course-classes/{id}/view-students:   
    get:
      summary: View all students in the class
      responses:
        '200':
          description: Succesfully view all students in the class
          content: 
            application/json:
              schema: 
                type: object
                properties:
                    student_user_id:
                      type: integer
                    name:
                      type: string    
        '404':
          description: Class not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string 


                
